"""Game record loading and access interfaces."""

from pathlib import Path
from wolf_llm_labeling.models import Label, PhaseItem, PhaseType, PlayerName, PlayerStatus, Role


class GameRecord:
    def read_from_files(self, paths: str | Path | list[str | Path]) -> None: ...

    def get_players(self) -> dict[PlayerName, Role]: ...

    def get_phase_type(self, phase_idx: int) -> PhaseType: ...

    def get_phase_data(self, phase_idx: int) -> list[PhaseItem]: ...

    def get_player_status(self, phase_idx: int, player_name: PlayerName) -> PlayerStatus: ...

    def get_labels(self, phase_idx: int) -> dict[PlayerName, dict[PlayerName, list[Label]]]: ...
